using System;
using System.Collections.Generic;
using System.IO;

namespace DungeonRunners.Data
{
    internal static class NativeAttributeIdentity
    {
        private static readonly string[] Names =
        {
            "PVP_DAMAGE_MOD",
            "STRENGTH",
            "AGILITY",
            "ENDURANCE",
            "INTELLECT",
            "SPEED",
            "SPEEDMOD",
            "MIN_SPEED_MOD",
            "IMMOBILE",
            "SIZEMOD",
            "ATTACK_RATING",
            "ATTACK_RATING_MOD",
            "ATTACK_SPEED_MOD",
            "DAMAGE_BONUS",
            "DAMAGE_MOD",
            "CRITICAL_CHANCE",
            "STUN_MOD",
            "MAGIC_CRITICAL_CHANCE",
            "STUN_RESIST",
            "SILENCE",
            "CRITICAL_DAMAGE_MOD",
            "HIT_POINT_STEAL",
            "MANA_POINT_STEAL",
            "FACTIONOVERRIDE",
            "FEAR_RESIST",
            "DEFENSE_RATING",
            "DEFENSE_RATING_MOD",
            "DAMAGE_REFLECT",
            "BLOCK",
            "DODGE",
            "DAMAGE_IMMUNITY",
            "DAMAGE_RESIST",
            "INVISIBLE",
            "MAX_HIT_POINTS",
            "MAX_MANA_POINTS",
            "HIT_POINT_REGEN",
            "MANA_POINT_REGEN",
            "HIT_POINT_REGEN_MOD",
            "MANA_POINT_REGEN_MOD",
            "HIT_POINT_REGEN_BONUS",
            "MANA_POINT_REGEN_BONUS",
            "MANA_COST_BONUS",
            "MAGIC_CRITICAL_CHANCE_MOD",
            "MELEE_ATTACK_RATING",
            "MELEE_ATTACK_RATING_MOD",
            "MELEE_ATTACK_SPEED_MOD",
            "MELEE_DAMAGE_BONUS",
            "MELEE_DAMAGE_MOD",
            "MELEE_CRITICAL_CHANCE_MOD",
            "MELEE_DEFENSE_RATING",
            "MELEE_DEFENSE_RATING_MOD",
            "MELEE_DAMAGE_REFLECT",
            "RANGE_ATTACK_RATING",
            "RANGE_ATTACK_RATING_MOD",
            "RANGE_ATTACK_SPEED_MOD",
            "RANGE_DAMAGE_BONUS",
            "RANGE_DAMAGE_MOD",
            "RANGE_CRITICAL_CHANCE_MOD",
            "RANGE_DEFENSE_RATING",
            "RANGE_DEFENSE_RATING_MOD",
            "RANGE_DAMAGE_REFLECT",
            "MELEE1H_ATTACK_RATING",
            "MELEE1H_ATTACK_RATING_MOD",
            "MELEE1H_ATTACK_SPEED_MOD",
            "MELEE1H_DAMAGE_BONUS",
            "MELEE1H_DAMAGE_MOD",
            "MELEE1H_CRITICAL_CHANCE_MOD",
            "MELEE2H_ATTACK_RATING",
            "MELEE2H_ATTACK_RATING_MOD",
            "MELEE2H_ATTACK_SPEED_MOD",
            "MELEE2H_DAMAGE_BONUS",
            "MELEE2H_DAMAGE_MOD",
            "MELEE2H_CRITICAL_CHANCE_MOD",
            "INTELLECT_MOD",
            "STRENGTH_MOD",
            "AGILITY_MOD",
            "ENDURANCE_MOD",
            "PRIMARY_ATTRIBUTE_MOD",
            "HEALTH_MOD",
            "MANA_MOD",
            "DAMAGE_PER_AGILITY_MOD",
            "DAMAGE_PER_INTELLECT_MOD",
            "DAMAGE_PER_STRENGTH_MOD",
            "MANA_PER_INTELLECT_MOD",
            "HEALTH_PER_ENDURANCE_MOD",
            "DEFENSE_RATING_PER_STRENGTH_MOD",
            "ATTACK_RATING_PER_AGILITY_MOD",
            "AGGRO_MOD",
            "MOLASSES_MOD",
            "AGGRO_BONUS",
            "CRUSHING_DAMAGE_MOD",
            "CRUSHING_DAMAGE_BONUS",
            "CRUSHING_DAMAGE_RESIST",
            "PIERCING_DAMAGE_MOD",
            "PIERCING_DAMAGE_BONUS",
            "PIERCING_DAMAGE_RESIST",
            "SLASHING_DAMAGE_MOD",
            "SLASHING_DAMAGE_BONUS",
            "SLASHING_DAMAGE_RESIST",
            "FIRE_DAMAGE_MOD",
            "FIRE_DAMAGE_BONUS",
            "FIRE_DAMAGE_RESIST",
            "FIRE_DAMAGE_WEAPON_ADD",
            "ICE_DAMAGE_MOD",
            "ICE_DAMAGE_BONUS",
            "ICE_DAMAGE_RESIST",
            "ICE_DAMAGE_WEAPON_ADD",
            "POISON_DAMAGE_MOD",
            "POISON_DAMAGE_BONUS",
            "POISON_DAMAGE_RESIST",
            "POISON_DAMAGE_WEAPON_ADD",
            "SHADOW_DAMAGE_MOD",
            "SHADOW_DAMAGE_BONUS",
            "SHADOW_DAMAGE_RESIST",
            "SHADOW_DAMAGE_WEAPON_ADD",
            "DIVINE_DAMAGE_MOD",
            "DIVINE_DAMAGE_BONUS",
            "DIVINE_DAMAGE_RESIST",
            "DIVINE_DAMAGE_WEAPON_ADD",
            "MAGIC_DAMAGE_MOD",
            "MAGIC_DAMAGE_BONUS",
            "MAGIC_DAMAGE_RESIST",
            "EXPERIENCE_IMMUNITY",
            "ATTACK_SILENCE",
            "EXPMOD",
            "CAST_SPEED_MOD",
            "IMMUNITY_MOD",
            "DAMAGE_TAKEN_MOD",
            "FIRE_DAMAGE_RESIST_MOD",
            "ICE_DAMAGE_RESIST_MOD",
            "POISON_DAMAGE_RESIST_MOD",
            "SHADOW_DAMAGE_RESIST_MOD",
            "DIVINE_DAMAGE_RESIST_MOD",
            "FIRE_DAMAGE_TAKEN_MOD",
            "ICE_DAMAGE_TAKEN_MOD",
            "POISON_DAMAGE_TAKEN_MOD",
            "SHADOW_DAMAGE_TAKEN_MOD",
            "DIVINE_DAMAGE_TAKEN_MOD",
        };
        private static readonly Dictionary<string, byte> Ids = CreateIds();

        private static Dictionary<string, byte> CreateIds()
        {
            var result = new Dictionary<string, byte>(StringComparer.Ordinal);
            for (int index = 0; index < Names.Length; index++)
                result.Add(Names[index], (byte)index);
            return result;
        }

        internal static string ResolveName(GCNode attribute)
        {
            string text = attribute.GetString("Attribute", string.Empty);
            if (!Ids.TryGetValue(text, out byte id))
                id = unchecked((byte)attribute.GetInt("Attribute", 0));
            if (id >= Names.Length)
                throw new InvalidDataException($"Attribute invalid ID={id} path={attribute.CanonicalPath}");
            return Names[id];
        }
    }
}
